### ISSUE TITLE
Selected text border/highlight when selecting is invisible

### ISSUE THREAD

**Issue by Wexx** [mokolabs/black-pearl-ii#1]
Not sure if this is intentional or not, but kind of a dealbreaker on this otherwise very pleasing theme

**Comment by mokolabs** [comment]
Hey, there.

It's not intentional. It's a bug. Things are in a slightly weird state because of the upcoming API changes for Atom themes.

If you haven't already, try unchecking `Use Shadow DOM` in your Atom settings.

**Comment by mokolabs** [comment]
Here's how it looks for me:

![screen shot 2015-03-23 at 11 13 45 am](https://cloud.githubusercontent.com/assets/444/6787100/ba51af94-d14d-11e4-83f6-d66c41b553ab.png)

**Comment by Wexx** [comment]
Ah, there it is. I had tinkered around with it and made it a really bright shade of red to test it out and see if that was athe issue, but it seems like that does the trick.

**Comment by mokolabs** [comment]
Cool. I'm glad it's working for you.

I'm closing this issue for now, but I'll update the README to note that `Use Shadow DOM` must be unchecked.

Also, I will revisit this issue once the Atom API change is final and make sure the theme is still working.

**Comment by dvon** [comment]
I fixed this a different way before finding the discussion here.  I modified base.less (new version below) so that its format matched that of another color scheme's base.less.  I'm brand new to Atom, though, so it's always possible what I did doesn't make sense :)

``` css
@import "syntax-variables";

:host, atom-text-editor {
  background-color: @syntax-background-color;
  color: @syntax-text-color;

  .gutter {
    background-color: @syntax-gutter-background-color;
    color: @syntax-gutter-text-color;

    .line-number.cursor-line {
      background-color: @syntax-gutter-background-color-selected;
      color: @syntax-gutter-text-color-selected;
    }

    .line-number.cursor-line-no-selection {
      color: @syntax-gutter-text-color-selected;
    }
  }

  .wrap-guide {
    color: @syntax-wrap-guide-color;
  }


  .indent-guide {
    color: @syntax-indent-guide-color;
  }

  .invisible-character {
    color: @syntax-invisible-character-color;
  }

  .search-results {
    .marker .region {
      background-color: transparent;
      border: @syntax-result-marker-color;
    }

    .marker.current-result .region {
      border: @syntax-result-marker-color-selected;
    }
  }

  .is-focused {
    .cursor {
      border-color: @syntax-cursor-color;
    }

    .selection .region {
      background-color: @syntax-selection-color;
    }

    .line-number.cursor-line-no-selection, .line.cursor-line {
      background-color: rgba(255, 255, 255, 0.05);
    }
  }
}

.text {
  color: #B4D3E2;
}

/* From here on it's just like the original... */
```
